### PR TITLE
Add necessary changes to upgrade to laravel.

### PR DESCRIPTION
**Pull request by gthomas125**
Some packages are unsupported in > PHP 7.1 (Cachehq mainly).

`GrahamCampbell\Exceptions` could use some work.

Have it working on PHP 7.4 Mac OS.

### CODE REVIEW

**Comment by evrifaessa** [comment]
Is this ready to test?

**Comment by awjudd** [comment]
@gthomas125 I just tried to run the tests, and they are failing.  Can you look into those issues?

**Comment by gthomas125** [comment]
> Is this ready to test?

Got it working but by no means perfect - will keep updating this PR.

**Comment by gthomas125** [comment]
> @gthomas125 I just tried to run the tests, and they are failing. Can you look into those issues?
> 
> ```
> PHP Fatal error:  Trait 'MailThief\Testing\InteractsWithMail' not found in /home/runner/work/okazanta-legacy/okazanta-legacy/tests/Bus/Events/Component/ComponentStatusWasChangedEventTest.php on line 25
> ```

Fab, thanks. Yes there's some old dependencies which haven't been updated in a while.

**Comment by gthomas125** [comment]
@awjudd Tests are performing but there's a lot of failures - I won't be able to pick this up again for a couple of weeks so feel free to jump in.

**Comment by evrifaessa** [comment]
You also should replace `fzaninotto/faker` with [`fakerphp/faker`](https://github.com/FakerPHP/Faker). The prior only supports PHP 7.x and is abandoned since 2020.

**Comment by evrifaessa** [comment]
You should add the following to the 219th line of `config/app.php` to make the array helpers accessible in Blade templates:

```
'Arr'          => Illuminate\Support\Arr::class,
```

Otherwise, some views like `dashboard/incidents/edit.blade.php` won't be able to use the Arr class and will throw an error.

**Comment by evrifaessa** [comment]
These packages are abandoned. Some of the failing tests are related to them:
- [`alt-three/bus`](https://packagist.org/packages/alt-three/bus)
- [`alt-three/validator`](https://packagist.org/packages/alt-three/validator)
- [`alt-three/testbench`](https://packagist.org/packages/alt-three/testbench)
- [`swiftmailer/swiftmailer`](https://packagist.org/packages/swiftmailer/swiftmailer)

**Comment by evrifaessa** [comment]
[This issue about GrahamCampbell/Laravel-Markdown](https://github.com/GrahamCampbell/Laravel-Markdown/issues/165#issuecomment-1040035928) should fix the following error:

```
Unexpected item 'commonmark'. (View: /(...)/resources/views/partials/incidents.blade.php) (View: /(...)/resources/views/partials/incidents.blade.php) (View: /(...)/resources/views/partials/incidents.blade.php)
```

**Comment by awjudd** [comment]
After further discussion, and given the overall scope and nature of this PR (i.e. it will be a breaking change across the board).  We have decided to close this PR and essentially use a lot of the hard work that was done during the initial rebuild of the application (i.e. when we migrate the code from here and the old version of Laravel into the "core" library).

Because of that, I will be closing this PR.

**Pull request closed without merging**
